# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 999efe7b534e7f1dc6f3ca5e39d22f3e8a0d710693df943c59cb188b9a32348f25681acb17f1c057e9331d2c798a4a9327876d6e3c4c4a421bb5f399c5b733f7

test:
  secret_key_base: b65b452c1c8b504b76c47b8afbdfcc2758891dcb71f10269910a0f542b11f1a445c9f31255a02ae766d84177e7a8b1e501530f95404e518809290c2ba56c46f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
